apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "master"
  
  workspaces:
    - name: source

  tasks:
    - name: init
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source

    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
      workspaces:
        - name: output
          workspace: source
      runAfter:
        - init

    - name: lint
      taskRef:
        name: checkstyle
      workspaces:
        - name: source
          workspace: source
      runAfter: 
        - clone

    - name: tests
      taskRef:
        name: run-tests
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - lint