apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-jacoco-pipeline
spec:
  workspaces:
    - name: source
  
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: https://github.com/ibm-developer-skills-network/miksg-ci-cd_Practicecode_j.git
        - name: revision
          value: main

    - name: maven-jacoco-report
      taskRef:
        name: maven-jacoco-report
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: source